#!/usr/bin/env python3
"""
Draws the OpenCode S40 mark with Pillow: opencode's wordmark, in opencode's
purple (#9a5feb, the accent their own theme maps primary/accent/info to).

  make_art.py icon OUT.png          46x48 MIDlet icon (transparent), in the JAR
  make_art.py logo OUT.png [SIZE]   large mark for README / share images

The letterforms come from mark_data.py, generated by tools/make_mark.py from
opencode's logo SVG, so the packaged icon and the on-screen mark (OcsMark.java)
are the same shape rather than two hand-drawn approximations.

Supersampled and downscaled for smooth edges. Deterministic output (no
timestamps in the PNG), which is what keeps the JAR byte-reproducible.
"""
import sys

from PIL import Image, ImageDraw

from mark_data import BASE, HEIGHT, OVERLAY, WIDTH

# opencode "purple" from their theme defs.
ACCENT = (0x9A, 0x5F, 0xEB, 255)
# The overlay cells are the counters of o/e/c and the crossbar of the e. They
# must be cut clean out of the body, so they are erased with alpha 0 before the
# body is painted. (In their logo the dark tone sits on top of the light one;
# for a transparent icon the same relationship is an erase.)


def wordmark(draw, cx, cy, height, color=ACCENT, over=None):
    """Draws the mark centred on (cx, cy) with the given height in pixels."""
    u = height / float(HEIGHT)
    x0 = cx - (WIDTH * u) / 2
    y0 = cy - height / 2

    for bx, by, bw, bh in OVERLAY:
        draw.rectangle(
            [x0 + bx * u, y0 + by * u,
             x0 + (bx + bw) * u - 1, y0 + (by + bh) * u - 1],
            fill=(0, 0, 0, 0) if over is None else over,
        )
    for bx, by, bw, bh in BASE:
        draw.rectangle(
            [x0 + bx * u, y0 + by * u,
             x0 + (bx + bw) * u - 1, y0 + (by + bh) * u - 1],
            fill=color,
        )


def render(w, h, fill_frac, bg=(0, 0, 0, 0), ss=8):
    """Supersamples, draws the mark, then downsamples for smooth edges.

    fill_frac is the fraction of the shorter side the mark's height should take,
    capped so the wordmark's width always fits with a margin.
    """
    big = Image.new("RGBA", (w * ss, h * ss), bg)
    d = ImageDraw.Draw(big)
    # Width is the binding constraint: 39x6 means height = width * 6/39.
    fit_w = (w * ss * 0.94) / float(WIDTH) * HEIGHT
    want = min(h * ss * 0.80, fit_w)
    wordmark(d, w * ss / 2, h * ss / 2, want)
    return big.resize((w, h), Image.LANCZOS)


def main():
    kind, out = sys.argv[1], sys.argv[2]
    if kind == "icon":
        # The wordmark is 39x6 grid units, so its height is only ~1/6 of its
        # width. On a 46x48 icon it must span nearly the full width to stay
        # legible, which leaves a mark about 7 px tall: thin, but crisp because
        # it is drawn at 8x and downsampled.
        img = render(46, 48, 1.0)
    elif kind == "logo":
        size = int(sys.argv[3]) if len(sys.argv) > 3 else 512
        img = render(size, size, 1.0)
    else:
        sys.exit("usage: make_art.py icon|logo OUT [SIZE]")
    img.save(out, optimize=False)


if __name__ == "__main__":
    main()