"""opencode wordmark block data, generated by tools/make_mark.py.

One unit is 1/6 of the mark height.
Tuples are (x, y, w, h) in grid units.
Keep in sync with src/io/github/maruf/ocs40/OcsMark.java.
"""

WIDTH = 39
HEIGHT = 6

# Letter bodies.
BASE = [
    (30, 0, 4, 3),
    (0, 1, 4, 2),
    (5, 1, 4, 2),
    (10, 1, 4, 3),
    (15, 1, 3, 2),
    (20, 1, 4, 2),
    (25, 1, 4, 2),
    (35, 1, 4, 3),
    (18, 2, 1, 4),
    (0, 3, 1, 3),
    (3, 3, 1, 3),
    (5, 3, 1, 3),
    (8, 3, 1, 3),
    (15, 3, 1, 3),
    (20, 3, 1, 3),
    (25, 3, 1, 3),
    (28, 3, 1, 3),
    (30, 3, 1, 3),
    (33, 3, 1, 3),
    (10, 4, 1, 2),
    (35, 4, 1, 2),
    (1, 5, 2, 1),
    (6, 5, 2, 1),
    (11, 5, 3, 1),
    (21, 5, 3, 1),
    (26, 5, 2, 1),
    (31, 5, 2, 1),
    (36, 5, 3, 1),
]

# Counters and crossbars, drawn on top.
OVERLAY = [
    (1, 3, 2, 2),
    (6, 3, 2, 2),
    (16, 3, 2, 3),
    (21, 3, 3, 2),
    (26, 3, 2, 2),
    (31, 3, 2, 2),
    (11, 4, 3, 1),
    (36, 4, 3, 1),
]
